### PR TITLE
Master

### PR DESCRIPTION
**Pull request by nicogis**
Added checkbox  'Build Network dataset'

### CODE REVIEW

**Comment by mmorang** [comment]
Hello @nicogis. Thank you for your contribution.

My team discussed this, and we decided that we do not want to include this option in the tool at this time.

I'm going to close the PR.  However, if you would like to give us some more information about why you added this option, and why you want to run the tool without building the network dataset, we would be happy to revisit and reconsider it.

**Comment by nicogis** [comment]
The reason is simple: if you have a very large dataset and you need to add few manual customizations after the tool’s operations, you have to wait for the tool’s build network dataset, add the customizations and then do manually the build again

**Comment by mmorang** [comment]
Hello again @nicogis. My team discussed this again, and we've changed our minds.  We are working to implement this option and will incorporate the changes from your PR (but we want to update one or two minor things).  Expect another PR soon.

Our initial hesitancy arose from the fact that the original version of the tool (years ago) did not build the network, and users complained and requested that the tool _should_ build the network.  This was the first request we had to _not_ build it.  We see now that it makes sense to give users the option.

**Comment by nicogis** [comment]
Ok thanks

**Comment by mmorang** [comment]
We did not merge this PR but added the desired functionality in https://github.com/Esri/street-data-processing-tools/pull/45.

**Comment by nicogis** [comment]
Ok, thanks

**Pull request closed without merging**
